services:
  db:
    image: postgres:16
    container_name: towerads_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - towerads_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  towerads_pgdata:

